name: ${name}
main: dev.byflow.psaddon.PSAddonPlugin
version: ${version}
author: BYFlow
api-version: '1.20'
depend:
  - ProtectionStones
commands:
  regiontnt:
    description: Gives PSAddon region TNT
    usage: /<command> [amount]
    permission: psaddon.regiontnt
permissions:
  psaddon.regiontnt:
    description: Allows receiving PSAddon region TNT
    default: op
